name: Build & Deploy KAVA Dashboard
on:
  push:
    branches:
      - develop
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.18.1"
  build:
    name: Build & Deploy
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v2.3.2
      # - name: Use Node.js 14
      #   uses: actions/setup-node@v2-beta
      #   with:
      #     node-version: "14.18.1"
      # - name: Install Dependencies
      #   run: yarn install
      # - name: 🔨 Build Project
      #   env:
      #     CI: true
      #   run: yarn build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          # source: ./build/*
          # target: /home/u432692730/domains/comfybroker.com/public_html/kavaclient
          script: pwd
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
